// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type GraphBrowserQuery = {
    scope: string;
    type?: string;
    query?: string;
    limit: number;
    provenance: boolean;
};

export type GraphScope = {
    id: string;
    name: string;
    kind: 'jurisdiction' | 'source' | 'reference';
    jurisdiction?: string;
    nodes: number;
    edges: number;
    node_types: {
        [key: string]: number;
    };
    relation_types: {
        [key: string]: number;
    };
    snapshot_id?: string;
    source_sha256?: string;
    coverage_status?: string;
    rights_status?: string;
};

export type GraphBrowserCatalog = {
    base_release_id: string;
    reference_pack_id: string;
    scopes: Array<GraphScope>;
    exact_identity_links: number;
    primary_graphs: number;
};

export type GraphBrowserResult = GraphData & {
    scope: string;
    matched_nodes: number;
    node_limit: number;
    truncated: boolean;
};

/**
 * EdgeData
 */
export type EdgeData = {
    /**
     * Id
     */
    id: string;
    /**
     * Start Id
     */
    start_id: string;
    /**
     * Predicate
     */
    predicate: string;
    /**
     * End Id
     */
    end_id: string;
    /**
     * Jurisdiction
     */
    jurisdiction: string;
    /**
     * Source Record Id
     */
    source_record_id: string;
    /**
     * Source Url
     */
    source_url: string;
    /**
     * Properties
     */
    properties: {
        [key: string]: unknown;
    };
    [key: string]: unknown;
};

/**
 * EntityData
 */
export type EntityData = {
    /**
     * Id
     */
    id: string;
    /**
     * Label Original
     */
    label_original: string;
    /**
     * Label En
     */
    label_en: string | null;
    /**
     * Type
     */
    type: string;
    /**
     * Jurisdiction
     */
    jurisdiction: string;
    /**
     * Source Record Id
     */
    source_record_id: string;
    /**
     * Source Url
     */
    source_url: string;
    /**
     * Properties
     */
    properties: {
        [key: string]: unknown;
    };
    [key: string]: unknown;
};

/**
 * GraphData
 */
export type GraphData = {
    /**
     * Nodes
     */
    nodes: Array<EntityData>;
    /**
     * Edges
     */
    edges: Array<EdgeData>;
    [key: string]: unknown;
};

export type GetGraphCatalogData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/graph/catalog';
};

export type GetGraphCatalogResponses = {
    /**
     * Regulatory scopes and independent reference scopes
     */
    200: {
        data: GraphBrowserCatalog;
    };
};

export type GetGraphCatalogResponse = GetGraphCatalogResponses[keyof GetGraphCatalogResponses];

export type PostGraphQueryData = {
    body: GraphBrowserQuery;
    path?: never;
    query?: never;
    url: '/graph/query';
};

export type PostGraphQueryResponses = {
    /**
     * Bounded graph with optional, explicitly marked provenance projection
     */
    200: {
        data: GraphBrowserResult;
    };
};

export type PostGraphQueryResponse = PostGraphQueryResponses[keyof PostGraphQueryResponses];

export type PostGraphExpandData = {
    body: GraphBrowserQuery;
    path?: never;
    query: {
        node_id: string;
    };
    url: '/graph/expand';
};

export type PostGraphExpandResponses = {
    /**
     * A bounded neighborhood in the selected scope
     */
    200: {
        data: GraphBrowserResult;
    };
};

export type PostGraphExpandResponse = PostGraphExpandResponses[keyof PostGraphExpandResponses];
